#if !defined(AFX_HWAUSB_H__1A6C61FB_0C70_43F4_B185_18E49D1E3DFD__INCLUDED_)
#define AFX_HWAUSB_H__1A6C61FB_0C70_43F4_B185_18E49D1E3DFD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CHwaUSB wrapper class

class CHwaUSB : public CWnd
{
protected:
	DECLARE_DYNCREATE(CHwaUSB)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x63b64d64, 0xb481, 0x4d8e, { 0x87, 0x26, 0x92, 0xf3, 0xb6, 0xcb, 0x58, 0x5e } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void Close();
	long Open(LPCTSTR SelPrinter);
	long PrintCmd(short data);
	long PrintStr(LPCTSTR data);
	long RealRead();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_HWAUSB_H__1A6C61FB_0C70_43F4_B185_18E49D1E3DFD__INCLUDED_)
