// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "hwausb.h"

/////////////////////////////////////////////////////////////////////////////
// CHwaUSB

IMPLEMENT_DYNCREATE(CHwaUSB, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CHwaUSB properties

/////////////////////////////////////////////////////////////////////////////
// CHwaUSB operations

void CHwaUSB::Close()
{
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

long CHwaUSB::Open(LPCTSTR SelPrinter)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		SelPrinter);
	return result;
}

long CHwaUSB::PrintCmd(short data)
{
	long result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		data);
	return result;
}

long CHwaUSB::PrintStr(LPCTSTR data)
{
	long result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		data);
	return result;
}

long CHwaUSB::RealRead()
{
	long result;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_I4, (void*)&result, NULL);
	return result;
}
